version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-light
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: childcompanion
      POSTGRES_PASSWORD: localdb
      POSTGRES_DB: childcompanion
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
